---
# handlers file for roles/database
- name: enable_mysql-server
  service:
    name: mysqld
    state: restarted
    enabled: yes

- name: restart_firewall_centos
  service:
    name: firewalld
    state: restarted
    enabled: yes

- name: start_mysql
  service:
    name: mysqld
    state: started