---
# handlers file for roles/webserver
- name: restart_and_enable_packages
  service:
    name: '{{ item.package }}'
    state: restarted
    enabled: yes
  loop:
    - {package: 'nginx'}
    - {package: 'php-fpm'}

- name: restart_ufw
  service:
    name: ufw
    state: restarted
    enabled: yes