ansible_user: cisco
ansible_password: cisco123!
ansible_python_interpreter: '/usr/bin/python3'
ansible_connection: "network_cli"
ansible_network_os: "ios"
ansible_become_method: enable
ansible_become_password: "cisco123!"