---
# tasks file for roles/common
- name : Update Ubuntu repo
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Upgrade pakketen van Ubuntu
  apt:
    upgrade: dist
    force_apt_get: yes
  when: ansible_facts['distribution'] == "Ubuntu"

- name: allow firewall accept ssh on ubuntu 
  ufw:
    rule: allow
    port: '22'
    proto: tcp
  notify:
    - restart_firewall_ubuntu
  when: ansible_facts['distribution'] == "Ubuntu"

- name : Update packages for CentOS 
  yum:
    name: '*'
    state: latest
  when: ansible_facts['distribution'] == "CentOS"

- name: allow firewall accept ssh on ubuntu 
  firewalld:
    port: 22/tcp
    state: enabled
    permanent: yes
  notify:
    - restart_firewall_centos
  when: ansible_facts['distribution'] == "CentOS"
