---
- name: Update software
  hosts: webservers, loadbalancers
  roles:
   - common


- name: Installeer webserver/packages
  hosts: webservers
  roles:
    - webserver

- name: Installeer and configure database 
  hosts: dbservers
  roles:
    - database

- name: Configure website
  hosts: webservers
  roles:
    - website-github

- name: Configure loadbalancer
  hosts: loadbalancers
  roles:
    - loadbalancer


- name: Edit hosts file and hostname
  hosts: controlhosts, webservers, loadbalancers
  roles:
    - varia

- name: Configure cisco router
  hosts: routers
  gather_facts: no
  roles:
    - routerconfig
