---
- name: Update software
  hosts: webservers, loadbalancers
  roles:
   - common


- name: Install webserver/packages
  hosts: webservers
  roles:
    - webserver

- name: Install and configure database 
  hosts: dbservers
  roles:
    - database
