---
- name: Update software
  hosts: webservers, loadbalancers
  roles:
   - common


- name: Install webserver/packages
  hosts: webservers
  roles:
    - webserver

- name: Install and configure database 
  hosts: dbservers
  roles:
    - database

- name: Configure website
  hosts: webservers
  roles:
    - website-github

- name: Configure loadbalancer
  hosts: loadbalancers
  roles:
    - loadbalancer